### ISSUE TITLE
On startup, error perfcounter plugin

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#10]
_Original author: Angelet...@gmail.com (December 17, 2010 22:53:24)_

ERROR:PerfCounter plugin: disktime: PdhEnumObjectItems error
ERROR:Failed to load PerfCounter plugin: [PerfCounterPlugin_disktime]
ERROR:PerfCounter plugin: processor: PdhEnumObjectItems error
ERROR:Failed to load PerfCounter plugin: [PerfCounterPlugin_processor]
ERROR:PerfCounter plugin: uptime: PdhEnumObjectItems error
ERROR:Failed to load PerfCounter plugin: [PerfCounterPlugin_uptime]

The 1.5v shows:
Failed to load PerfCounter plugin: [PerfCounterPlugin_disktime]
Failed to load PerfCounter plugin: [PerfCounterPlugin_processor]
Failed to load PerfCounter plugin: [PerfCounterPlugin_uptime]

whats wrong?

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=5_

**Comment by CWempe** [comment]
Maybe #70 does solve this issue.

**Comment by lemontree23** [comment]
Outdated issue (opened 8 years ago)
