### ISSUE TITLE
Multiple Performance Counters on Single Graph

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#11]
_Original author: jcss...@gmail.com (January 31, 2011 04:45:03)_

Copied from SF.NET Forums

From: yuichiyoda
Date: 2010-10-01 01:29:15 CDT

Is there a way to get multiple performance counters(not instances) in one graph?
I would like to plot usage of CPU (user% , system%, etc.) in one graph like munin-node of Linux's.

Thanks in advance

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=6_

**Comment by thewabbit0** [comment]
FWIW, I've created a new external plugin which handles the _"multiple datalines in a single graph"_ requirement and allows for high-resolution graphs (down to 1 data sample per second):

https://github.com/thewabbit0/perfmon2munin

**Comment by lemontree23** [comment]
Closing this issue since it is 6 years old, and @thewabbit0 developed a plugin that solves this
