### ISSUE TITLE
Network plugin shows packets not bytes

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#12]
_Original author: cameron....@gmail.com (February 02, 2011 05:14:21)_

<b>What steps will reproduce the problem?</b>
1. install munin-node-win32
2. telnet localhost 4949
3. &quot;config network&quot;

<b>What is the expected output? What do you see instead?</b>

I think most people would rather see bytes/s rather than packets/s. 

The inability to find out how much traffic a system is doing is a key missing function.

<b>What version of the product are you using? On what operating system?</b>

windows, 1.6.0

<b>Please provide any additional information below.</b>

You totally rock for bringing this project back from the dead. Munin rocks and it is sad not to have a windows client. Pity Im horrid at windows programming. ;-(

Cross fingers that it's just a different counter or a simple fix.

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=7_

**Comment by lemontree23** [comment]
Feature not bug...
Also Outdated issue (opened 8 years ago)
