### ISSUE TITLE
installer: do NOT overwrite munin-node.ini if it exists!

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#14]
_Original author: agros...@gmail.com (February 07, 2011 12:22:55)_

installer: do NOT overwrite munin-node.ini if it exists!

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=9_

**Comment by CWempe** [comment]
implemented by https://github.com/rrzefox/munin-node-win32/commit/0062f3f77e3a9dd89c7f7899b6306dc891910313

**Comment by lemontree23** [comment]
Will change in newest installer
