### ISSUE TITLE
after an exception, it's stuck at "starting server thread"

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#16]
_Original author: agros...@gmail.com (February 11, 2011 12:02:03)_

Faulting application name: munin-node.exe, version: 1.6.0.0, time stamp: 0x4b517bff
Faulting module name: munin-node.exe, version: 1.6.0.0, time stamp: 0x4b517bff
Exception code: 0x40000015
Fault offset: 0x00007b54
Faulting process id: 0x2210
Faulting application start time: 0x01cbc972a23df563
Faulting application path: C:\Program Files (x86)\Munin Node for Windows\munin-node.exe
Faulting module path: C:\Program Files (x86)\Munin Node for Windows\munin-node.exe

On the next (automatic) restart by the service manager the node is stuck at &quot;Starting Server Thread&quot; never gets to &quot;Server Thread Started&quot;.
Therefore it does not accept connections.
Service restart does not help either.

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=11_

**Comment by lemontree23** [comment]
Outdated issue (opened 8 years ago)
