### ISSUE TITLE
PerfCounterPlugin only gives 0 values after windows update.

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#24]
_Original author: moroni.n...@interoute.com (May 16, 2011 14:29:43)_

<b>What steps will reproduce the problem?</b>
1. Updating windows 2008 R2 to latest patches using windows update.
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
Gen0Collections.value 106.000
.
Gen0Collections.value 0.00
.

<b>What version of the product are you using? On what operating system?</b>
munin-node 1.5.1942 &amp; 1.6. Windows 2008 R2

<b>Please provide any additional information below.</b>
when using vbs script with following command
objShell.Run &quot;%comspec% /c &quot;&quot;typeperf &quot;&quot;&quot; &amp; object &amp; &quot;(&quot; &amp; instance &amp; &quot;)&quot; &amp; counter &amp; &quot;&quot;&quot; -sc 1 &gt; &quot; &amp; filename &amp; &quot;&quot;&quot;&quot;, 0, True
to write a file with the performance counter value. The value in the temporary file is 0 as well. But it works when running from command prompt.
Using a scheduled task to update a static file with the values gives me 
fetch Gen0Collections
Gen0Collections.value 106.000000
.

But when trying to use the external script graphing the munin-node does simple not work and I get for example
2011/05/16 16:25:30 [WARNING] Call to accept timed out.  Remaining workers: 
and after about 2 minutes
2011/05/16 16:27:02 [FATAL] Socket read timed out to

Even if it seems to work when using telnet and running the commands from shell.

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=19_

**Comment by kefealo** [comment]
same situation with plain win32/cmd file :)

**Comment by sumpfralle** [comment]
Is the plugin writing to a file? Could there be a permission problem?
