### ISSUE TITLE
Installer: enables firewall only on Public networks

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#26]
_Original author: david.black.co.at@gmail.com (June 10, 2011 07:42:14)_

<b>What steps will reproduce the problem?</b>
1. Install munin-node-win32
2. Request the installer to punch a hole in the firewall
3. Inspect firewall settings (e.g. &quot;Allow programs through Windows Firewall&quot;)

<b>What is the expected output? What do you see instead?</b>

I'd expect munin to be allowed on all networks (perhaps except Public networks) but it is _only_ allowed on Public networks.

<b>What version of the product are you using? On what operating system?</b>

1.6, on Windows 7 Ultimate N SP1 64bit

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=21_

**Comment by CWempe** [comment]
I think a solution would be to use the following NSIS plugin.
http://nsis.sourceforge.net/NSIS_Simple_Firewall_Plugin

What are the "best" settings to use?

- tcp/4949 obviously
- "all networks" or only the local subnet?
I think all is ok. You cannot expect the munin server to be in the same subnet. But most security will be handelt by corparate firewall anyway.
- For all network types (private, public, domain) or just domain and private?
