### ISSUE TITLE
Sensors - HDD temp should be made external

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#27]
_Original author: tomse0...@gmail.com (July 04, 2011 13:16:46)_

<b>What steps will reproduce the problem?</b>
1. Install a Windows on a VM and monitor it

<b>What is the expected output? What do you see instead?</b>
sensors disabled - Seing &quot;missing icons&quot; where graph for HDD temp should be

<b>What version of the product are you using? On what operating system?</b>
1.6 - Win2003 Svr

<b>Please provide any additional information below.</b>
Sensors shouldn't be placed as built-in as they aren't supported on all systems.

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=22_

**Comment by lemontree23** [comment]
You can disable graphs in the config.
