### ISSUE TITLE
PerfCounterPlugin problem with Czech locales

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#29]
_Original author: michal.p...@gmail.com (August 25, 2011 12:29:49)_

After i read http://code.google.com/p/munin-node-win32/issues/detail?id=3 i though i solved my problem but only what i found there is a problem with czech ascii like: &quot;ěščřžýáíéúů&quot;.

Is it problem in API what are you using or in your script? Every object or counter without special ascii character works fine.

I try install 1.6.1 beta but there is the same problem.

ERROR:PerfCounter plugin: disktime: PDH add counter error=c0000bb9
RROR:Failed to load PerfCounter plugin: [PerfCounterPlugin_disktime]
RROR:PerfCounter plugin: processor: PDH add counter error=c0000bb9
RROR:Failed to load PerfCounter plugin: [PerfCounterPlugin_processor]
ERROR:PerfCounter plugin: uptime: PdhEnumObjectItems error=c0000bb8
ERROR:Failed to load PerfCounter plugin: [PerfCounterPlugin_uptime]
ERROR:PerfCounter plugin: smtpmessagessent: PdhEnumObjectItems error=c0000bb8

Errorlist from MSDN:
0xC0000BB8 (PDH_CSTATUS_NO_OBJECT)  The specified object is not found on the system.
0xC0000BB9 (PDH_CSTATUS_NO_COUNTER) The specified counter could not be found.

Thank you in advance for your reply.

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=24_

**Comment by CWempe** [comment]
Maybe #70 does solve this issue.

**Comment by kefealo** [comment]
munin-node.ini not UTF-8 formatted.

**Comment by sumpfralle** [comment]
@kefealo: I am not sure, how to interpret your hint. Is this related to the problem above? Should be something done about it?
