### ISSUE TITLE
External plugin problem

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#33]
_Original author: xne...@gmail.com (October 06, 2011 12:15:05)_

Here's the config:

[Plugins]
; Plugin Section, 1 enables plugin, 0 disables
Disk=1
Memory=1
Processes=1
Network=1
HD=0
Cpu=1
External=1
ExternalTimeout=30

[ExternalPlugin]
Plugin01=&quot;C:\munin\PowerShellLauncher.exe C:\munin\vm_bytes_received.ps1&quot;

But when I connects to munin-node the plugin is not visible:

Connected to SOME_IP.
Escape character is '^]'.
# munin node at WIN-KO4G0OHA17A

list
df memory processes network cpu

Am I doing something wrong?
Thanks.

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=28_

**Comment by kefealo** [comment]
Hi! Where do you found the powershelllaucher.exe?
Any news? I'm fighting with the Hungarian Windows 2008R2 performance monitor string translations. I decided to write some powershell plugin scripts and working from cmd and working from ps, but from munin-node timing out with 30 seconds...

**Comment by sumpfralle** [comment]
The original problem seems to be that the prompt of munin-node is not transmitted/visible.
But it still works, or?
