### ISSUE TITLE
munin.ini improvement

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#34]
_Original author: sol...@gmail.com (December 16, 2011 12:01:02)_

<b>What steps will reproduce the problem?</b>
1. see munin.ini

<b>What version of the product are you using? On what operating system?</b>
1.6.1.0 beta on Windows 7 64bit edition

<b>Please provide any additional information below.</b>
If [ExternalPlugin] section contains plugins which doesn't exist, it makes junk outputs ( &quot;file does not exist&quot; ) on &quot;list&quot; command.
And in my system, commenting out Plugin00 and Plugin01 lines fixed this problem.
So, I recommend commenting out Plugin00 and Plugin01 lines on munin.ini or checking the existence of external plugin file.

(I don't know if this problem also happens on non-Japanese Edition of Windows.)

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=29_

**Comment by lemontree23** [comment]
It is done... :)
