### ISSUE TITLE
Service stops running

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#35]
_Original author: marc@engrie.be (February 25, 2012 07:04:07)_

<b>What steps will reproduce the problem?</b>
1. munin-node -run 
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
program show run 'forever' (as it was a service)

<b>What version of the product are you using? On what operating system?</b>
1.5.1942 on Windows 7 ultimate 64 bit 

<b>Please provide any additional information below.</b>
The program quits after a few seconds. 
I tried this with the released version 1.5.1942 as well as with the latest source compiled with VC++ 2010.
It happens with a standard .ini file as well as with a reduced one (=only 1 resource to monitor).

outputs attached

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=30_

**Comment by lemontree23** [comment]
well....  years later and yeah... If you run the service from the command line like `munin-node -run` it only runs until the server tries to get data. If it is registered as a windows service it runs indefinitely.
