### ISSUE TITLE
-uninstall and -install corrupts system 

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#37]
_Original author: ivanr...@gmail.com (March 28, 2012 13:40:26)_

I'm not going to attempt repeat to re-create the symptoms as this was a critical issue, and I had to restart my system to avoid further problems.
I am new to munin, and was simply exploring the files that had been installed on my system.
1. installed using munin-node-win32-1.6.0.0-installer.exe
2. clicked the munin-node shortcut in the start menu and then closed the opened shell window right after.
3. created a munin-node.exe -uninstall shortcut and clicked it to test
4. created a munin-node.exe -install shortcut and clicked it to test
5. restarted the munin service in services.msc
   This was exactly how I did it. I had the Event Viewer opened all the time to look for errors.

At step 3, I instantly saw that the &quot;Source&quot; column in the Event Viewer was now blanked out (data deleted). This sort of freaked me out, but I guessed maybe this was something that would be sorted out on the next login or reboot.

Well, that was what I though until I tried right clicking a file on my desktop... Symantec Antivirus (already installed on my system) would then launch it's installer. I clicked cancel.
I try right clicking again. Same thing again.
Any file or folder i right click will instantly produce the same problem. After the SAV installer is launched, the right click context menu is displayed as normally.

I try logging out, and logging back in. It doesnt help. Event Viewer &quot;source&quot; column is still blanked out.

I quickly uninstall Munin Node for Windows using the provided exe.

Reboot.

And now right click works like it should.
But my event Application log is empty (deleted) - there is only data there from current boot time - the &quot;Source&quot; column is working ok - but all applications are giving the same type of error message. They will start ok, but giving this error message in Event Viewer...

The description for Event ID ( 1 ) in Source ( WinVNC4 ) cannot be found. The local computer may not have the necessary registry information or message DLL files to display messages from a remote computer. You may be able to use the /AUXSOURCE= flag to retrieve this description; see Help and Support for details. The following information is part of the event: ../..

So, care to explain what your software has done to my system?

Windows 2003 Standard Edition English x32

Let me know if more info is needed.

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=32_

**Comment by lemontree23** [comment]
Seems to be patched
