### ISSUE TITLE
Windows 8 Compatibility : cannot open service manager

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#39]
_Original author: alistair...@gmail.com (May 24, 2012 02:34:06)_

<b>What steps will reproduce the problem?</b>
1. Run munin-node.exe -install

<b>What is the expected output? What do you see instead?</b>
The service should be installed without any output (as tested on a Win7 x64 system). Instead, a dialog box appears, reading &quot;Couldn't open service manager&quot;, indicating hSCM handle didn't work correctly.

<b>What version of the product are you using? On what operating system?</b>
I'm using v1.6.0 (stable) on a Windows 8 Consumer Preview system

<b>Please provide any additional information below.</b>
I'm not sure if this is a generic compatibility problem with Windows 8 or if I've got some other problem appearing.
Also note that running munin-node.exe -run results in the usual procedure of all the plugins loading, the server thread starting then stopping after a short delay.

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=34_

**Comment by lemontree23** [comment]
You need to run the command as Administrator, since regular users cannot modify services. The newest install will do it for you since it runs as Admin.
