### ISSUE TITLE
No CPU statistics on Windows Server 2008R2

### ISSUE THREAD

**Issue by thabich** [munin-monitoring/munin-node-win32#44]
Hi!
The CPU statistic always gives a 0.00 value on Windows Server 2008R2

fetch cpu
cpu_user.value 0.000000
.

**Comment by kcwhited** [comment]
I just wanted to add that I still have this same issue.  I wish I had the skills to help with this software.  CPU stats works on Windows 2008 but Windows 2008r2 & Windows 7 is a no-go.  The rest of the statistics seem to work find in munin but cpu stats reports 0

**Comment by o1e9** [comment]
The same problem on all hosts with Windows Server 2008R2 and 7 SP1 however works for Windows Storage Server 2012.

**Comment by dangson** [comment]
If you guys are still having this problem, check out the builds by TcT2k here:
https://github.com/munin-monitoring/munin-node-win32/issues/47

The 1.6.1 build solved the issue for me on Windows 7.

**Comment by Strykar** [comment]
TcT2k's build does not solve the lack of CPU graphs for me on Win 10 Pro x64.

**Comment by lemontree23** [comment]
The CPU issues should be fixed in the newest version, check in the 'releases' tab
