### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#6]
_Original author: agros...@gmail.com (May 31, 2010 18:59:07)_

On windows 2008 R2 server

Faulting application name: munin-node.exe, version: 1.6.0.0, time stamp: 
0x4b517bff
Faulting module name: munin-node.exe, version: 1.6.0.0, time stamp: 
0x4b517bff
Exception code: 0x40000015
Fault offset: 0x00007b54
Faulting process id: 0x39ac
Faulting application start time: 0x01cafdc6dc56de6b
Faulting application path: C:\Program Files (x86)\Munin Node for 
Windows\munin-node.exe
Faulting module path: C:\Program Files (x86)\Munin Node for Windows\munin-
node.exe
Report Id: 90534b3a-69d7-11df-bc6f-003048dda0fe

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=1_

**Comment by lemontree23** [comment]
Outdated issue (8 years)
