### ISSUE TITLE
Samsung SSD temps not reported

### ISSUE THREAD

**Issue by Strykar** [munin-monitoring/munin-node-win32#65]
The issue seems related to https://github.com/munin-monitoring/contrib/issues/15
I tried with a new SSDMuninNodePlugin.cpp and <code>ST_SMART_INFO *pSmartInfo = g_SmartReader.GetSMARTValue(pDriveInfo->m_ucDriveIndex, SMART_ATTRIB_AIRFLOW_TEMPERATURE);</code> but it will not report the Samsung 850 EVO temp.

<pre>Name: hdd
Config:
graph_title HDD temperature
graph_args --base 1000 -l 0
graph_vlabel temp in C
graph_category sensors
graph_info This graph shows temperature in degrees Celsius of the hard drives.
_hdd_0_.label ST31000528AS
_hdd_1_.label SamsungSSD 850 EVO 250GB
_hdd_2_.label WDCWD10EADS-00M2B0
_hdd_3_.label WDCWD10EARS-00Z5B1
.

Value:
_hdd_0_.value 39
_hdd_2_.value 40
_hdd_3_.value 37
.</pre>

It detects the drive just fine and can run diskfree.py on it.
This would seem like an easy fix but I've had no success this far.

**Comment by lemontree23** [comment]
Is only shows it on the graph if the SSD reports it. If it does not show up on the graph it means that your SSD does not report airflow temperature as a SMART value.
