### ISSUE TITLE
Is there up-to-date binaries for Win 7, here or elsewhere ?

### ISSUE THREAD

**Issue by Naereen** [munin-monitoring/munin-node-win32#68]
Hi,
I tested about half-a-dozen of forks on `munin-node-win32` on Windows 7 and 8 (this one, and the latest active forks from [its network](https://github.com/munin-monitoring/munin-node-win32/network)).
All of them run well at first, but all fail quickly without exception, just saying [`"Stopping Server Thread"`](https://github.com/munin-monitoring/munin-node-win32/blob/master/src/core/Service.cpp#L168), for no reason.
> There isn't any command line option to printout a traceback or a log, so I am sorry but cannot give more detail :cry:... 

### Bug
If my `munin-server` is quick enough, it successively connects to the Win32 server once or twice before it fails, even acquiring some data, which are perfectly correct.
So I guess the program (and all the basic plugins) works fine, but some nasty behavior is making it stop (let's call that a bug).

### Questions
- *First question:* does any one already heard about that bug Any idea how I could fix it? (I don't know enough on C++ and C++ debugging to find out what to do myself).

- *Second question:* is there anyone in charge of this repository? Some forks have been updated recently, but the "official" repo seems to not be active anymore. Can anyone suggest a fork, *with* compiled binary, working fine for Win 7 ?

Thanks in advance.

**Comment by Naereen** [comment]
Anyone?

**Comment by lemontree23** [comment]
For those of you guys looking at this in 2020, I took it upon myself to fix up some non-working code and also add a lot o new S.M.A.R.T plugins.
I also built a binary installer for you so you do not have to do anything.
https://github.com/lemontree23/munin-node-win32/releases/tag/1.7.3.0

**Comment by sumpfralle** [comment]
@lemontree23: that sounds great!

@jcsston / @agroszer: what do you think about these changes?

**Comment by Alexsae24** [comment]
I like it too, but my Windows virtual, most sensors switched off :-)

**Comment by lemontree23** [comment]
Binaries now in 'Releases' tab
