### ISSUE TITLE
Merging contributions from lemontree23

### ISSUE THREAD

**Issue by sumpfralle** [munin-monitoring/munin-node-win32#79]
The repository of @lemontree23 contains many improvements:
* build system and installer updates
* improvements of the SMART plugins

The are surely worth to be integrated into this repository.

@lemontree23: I took a closer look at your [set of changes](https://github.com/lemontree23/munin-node-win32) (with my limited understanding of Window's build and installer environment). I think, your additions are very helpful - especially the possibility to use munin-node-win32 on newer Windows systems. Since the current members of the `munin-node-win32` team (@jcsston, @agroszer) are not very active at the moment, it would be nice, if you could join the team and merge your work into the official repository. What do you think?

While reviewing your commits I stumbled upon the following minor details. Maybe some of my comments are useful:
* A) I do not understand the new section `GlobalSection(ExtensibilityGlobals)` (see [here](https://github.com/lemontree23/munin-node-win32/blob/9b9617dfa68c8eff4d9b0adad0ca4e8f5cd439ff/munin-node.sln#L29)). The introduced UUID seems to be local to your system?
* B) You uploaded binary release builds ([here](https://github.com/lemontree23/munin-node-win32/commit/ec69078a6bafb8e2e62f99021d2492af01ef6291) and [here](https://github.com/lemontree23/munin-node-win32/commit/a6a941a9bd74ff8c15ea9199a9c19ee3e9e92f88)) to the repository. Instead [binary build artifacts should be attached to releases](https://help.github.com/en/github/managing-large-files/distributing-large-binaries) or (if you want more control independent of github) stored in a separate release repository with git's LFS feature enabled. Otherwise the source repository grows out of bounds over the years.
* C) What is the purpose of "echo" and "pause" in the [service installation script](https://github.com/lemontree23/munin-node-win32/blob/f6cc18438b981911875dbdbd80ee5d30541cb354/Installer%20Files/Install-Service.bat)?
* D) [Commit 5835850b009](https://github.com/lemontree23/munin-node-win32/commit/5835850b0092f8fa2981a20a14e87aa8d478cfce) switched a plugin's category to an unusual key (see [munin's well-known plugin categories](http://guide.munin-monitoring.org/en/latest/reference/graph-category.html#well-known-categories)). You should probably stick to the well-known set of categories.
* E) The [commit b72516c14](https://github.com/lemontree23/munin-node-win32/commit/b72516c14766ebe16b5fb22061022cbd689925e6) commented out a big chunk of code (see "NtQuerySystemInformation" - lines 90..138). Probably you should simply remove the code, if it is of no use anymore. At least the current diff of the commit was quite hard to read. Another commit ([28dccaf39](https://github.com/lemontree23/munin-node-win32/commit/28dccaf3911d49c1730e4eb290045de8839b6274)) also comments out a big chunk of code.
* F) [Commit b72516c14766ebe16b5fb22061022cbd689925e6](https://github.com/lemontree23/munin-node-win32/commit/b72516c14766ebe16b5fb22061022cbd689925e6) Introduced a duplicate set of "graph_order" (both containing unused field names) into `CpuMuninNodePlugin`.
* G) You introduced multiple new smart plugins (which is good!). Maybe you could merge these into *one* multigraph plugin instead (multiple graphs created by one plugin)? This would reduce code duplication.
* H) [Commit a6a941a9](https://github.com/lemontree23/munin-node-win32/commit/a6a941a9bd74ff8c15ea9199a9c19ee3e9e92f88) seems to disable "SpeedFan" and "External"? Was that intentional?
* I) I do not understand the purpose of the `munin-node.aps` file? It contains private paths - thus it is probably not useful / a source of conflicts for others. Maybe remove it from the repository and add it to `.gitignore`? 
* J) `Installer Files/Munin-node-x86.iss` and `Munin-node-x64.iss` are almost identical - maybe there is a way to reduce the code duplication?
* K) Maybe you want to take a look at this [blog post about git commit messages](https://chris.beams.io/posts/git-commit/). I think, it describes a rather widespread style. In your case: maybe you want to switch to an *imperative* style (e.g. "Fix ..." instead of "Fixed ...").

Please understand the above notes just as hints. I cannot stop myself taking notes while reviewing code :)

What do you think? Would you like to take care for `munin-node-win32` here inside of the munin project?

@jcsston, @agroszer: feel free to join this discussion.

(disclaimer: I am not active in `munin-node-win32` - I am just one of the maintainers of the `munin` and the `contrib` repository)

**Comment by lemontree23** [comment]
A) I also do not know what that is, VS did it
B) I also have realeases
C) It cleans up the command line output and allows the user to see errors otherwise the commandline will just close
D) At my workplace we want to see certain SMART values per Hard Drive, with it in a seperate category it is easier to find.
E) I wanted to see the previous code and forgot to delete it  :P 
F) Didnt't see that....
G) Every smart plugin shows the value per drive, so multiple drives will create a multigraph
H) It disables it by default, Speedfan does not work, and by default there are no external plugins, you can still enable it after install.
I) I'll remove it
J) The two files point to different executables, I do not know of a way to combine them.
K) will do


I am not at all good at C++. I just fixed the program wand added what we needed to monitor pc's in our office.

**Comment by sumpfralle** [comment]
A few comments:

> C) It cleans up the command line output and allows the user to see errors otherwise the commandline will just close

In this case I would suggest to run "pause" only in case of an error.
Regarding the `cls`: personally I do not appreciate  programs clearing my screen. In the Windows environment I can imagine, that the script is either called in an existing terminal (which you should leave untouched, I think) or in a new terminal (which starts as empty). Thus probably you can remove it? Anyway: this is just for the taste - feel free to ignore my comments.


> D) At my workplace we want to see certain SMART values per Hard Drive, with it in a seperate category it is easier to find.

*switching to maintainer's voice*: in this case you should either add the ability to configure the `graph_category` via an environment variable or wait for munin 3.0 (see [#1160](https://github.com/munin-monitoring/munin/issues/1160)). The latter may take a bit of time ...


> G) Every smart plugin shows the value per drive, so multiple drives will create a multigraph

I think, we are talking about different things. I wanted to refer to [munin's multigraph plugins](http://guide.munin-monitoring.org/en/latest/plugin/multigraphing.html). They allow you to achieve one of the following designs (or a mixture of both):
* a) generate multiple top-level graphs out of a single plugin
* b) generate a top-level graph ("a summary") and multiple sub graphs (visible only after expanding the top-level graph)

This would allow you to write a single plugin for all the trivial SMART attributes, which reduces code duplication significantly.

>  J) The two files point to different executables, I do not know of a way to combine them.
Maybe the check `Is64BitInstallMode` (see [blog post](https://blog.csdn.net/suzhi921/article/details/7908345)) could be used. Anyway: just a matter of taste and reduced duplication ...

> I am not at all good at C++. I just fixed the program wand added what we needed to monitor pc's in our office.

This is a good start. You are welcome to join the `munin-node-win32` "team", if you like. It will take a bit of time (depends on you), but it will give you the good warm feeling of thankfulness from all your fellow munin users in Windows. What do you think?

**Comment by lemontree23** [comment]
As I am currently working full time I will have to think about joining the team, but thanks for the feedback anyway :)

**Comment by sumpfralle** [comment]
> As I am currently working full time [..]

You shall not worry about such minor details :)

As far as I know the other people involved with munin (including myself), they are also working in unrelated jobs. It is a leisure activity - thus people decide on their own, how much time they want to spend on it.

I estimate that `munin-node-win32` can reach quite a good state of maintenance with one hour of time peer week. In the beginning a burst of activity would be great for filtering out and working through the open issues and pull requests. But of course, this can also be stretched over weeks or month (still being a great improvement over the current state of maintenance).

**Comment by lemontree23** [comment]
Ok sure yeah I'll do it.... It seems fun :)

**Comment by sumpfralle** [comment]
Welcome!

Now that you are part of the munin-node-win32 team: feel free to clean up, merge, improve and have fun!

**Comment by lemontree23** [comment]
Imma close this now.... :)
