### ISSUE TITLE
the cpu plugin returns zero all the time on Win7-x64 only

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#8]
_Original author: netll...@gmail.com (August 19, 2010 21:03:47)_

This works as expected on WINXP (32 &amp; 64bit), VISTA (32 &amp; 64bit) and Win7-i686.  The only place where it fails is Win7-x86_64.

<b>What is the expected output? What do you see instead?</b>
the cpu plugin returns zero all the time:
$ rrdtool fetch win764-test0-cpu-cpu_user-g.rrd AVERAGE -s -15M
1282251000: 0.0000000000e+00
1282251300: 0.0000000000e+00
1282251600: 0.0000000000e+00

 even though the Processor Time plugin works fine:
$ rrdtool fetch win764-test0-processor-processor-g.rrd AVERAGE -s -15M
1282251000: 2.5252877200e+01
1282251300: 4.1204490334e+01
1282251600: 7.9287256530e+01

<b>What version of the product are you using? On what operating system?</b>
1.6.0.0-munin-node on Win7-x64 (Enterprise)

<b>Please provide any additional information below.</b>
This bug is also present with the 'original' munin-node-win32:
http://sourceforge.net/projects/munin-nodewin32/forums/forum/921022/topic/3807654

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=3_

**Comment by lemontree23** [comment]
Outdated issue (8 years), also fixed in newest
