### ISSUE TITLE
Make downloadable exe

### ISSUE THREAD

**Issue by Mikki-black** [munin-monitoring/munin-node-win32#85]
Unless I'm very wrong, I don't see any downloadable installer file. Would it be possible to include it? I managed to build it myself, but it's timeconsuming. It's much easier to download and install it or even beter use it in chocolatey which I'm willing to maintain. I can host it myself of course, but it's easier if it's part of the project.

**Comment by yannik995** [comment]
Here you can find the downloadable exe files: 
https://github.com/munin-monitoring/munin-node-win32/releases

**Comment by lemontree23** [comment]
Yes, all updated version will be posted in the releases tab of the repositiry
