### ISSUE TITLE
silent command-line installation

### ISSUE THREAD

**Issue by sdarwin** [munin-monitoring/munin-node-win32#87]
Hi,

I would like to install munin node from an automated script. This does not seem to work:

```
.\Munin-Node-1.7.3.2-x64.exe -quiet
```
The reason being, that all the command line options -install, -uninstall, -quiet, -run do the exact same thing which is launch a typical interactive windows installer popup, running an installation.    None of those flags seem to have an effect. 

operating system: Windows Server 2019 Datacenter

**Comment by amartinmassoni** [comment]
You can find all the command line parameters with **.\Munin-Node-1.7.3.2-x64.exe /?**
 **.\Munin-Node-1.7.3.2-x64.exe /quiet** worked for me.

**Comment by sumpfralle** [comment]
> The reason being, that all the command line options -install, -uninstall, -quiet, -run do the exact same thing [..]

@sdarwin: are these commandline arguments documented somewhere? In case you did not find any documentation for commandline arguments: where would you expect these?

(just asking for the purpose of better documentation)

**Comment by sdarwin** [comment]
> are these commandline arguments documented somewhere? 

-install, -uninstall, -quiet, -run are in the README file.

> In case you did not find any documentation for commandline arguments: where would you expect these?

In README.rst,  /quiet and /? aren't mentioned.

**Comment by sdarwin** [comment]
@amartinmassoni thanks for the help.

- /? shows the help screen
- /silent runs a silent install
- /quiet doesn't have any effect

It would probably be a good idea to explain /? and /silent in the documentation, clarifying those flags apply to the installer.    The other flags -install, -uninstall, -quiet, -run, (assuming those are valid) likely apply to the munin executable itself and not to the installer.

**Comment by singularcitrus** [comment]
I have been receiving a lot of discussion emails from github today. A you can see, my last commit was a very long time ago. 

Let me quickly clarify, any flag that starts with `-`, like `-quiet` applies to the application itself, not the installer. The last time I checked there was a weird bug with the `-quiet` flag and it didn't work. If you can manage to fix it, feel free to open a PR and I will most likely approve it.

As for the flags on the installer, we make use of [InnoSetup ](https://jrsoftware.org/isinfo.php) to generate the installer, and have not defined any specific flags. So for all installer flags you should consult the InnoSetup documentation.
