### ISSUE TITLE
Munin-node exec for windows flagged as malicious

### ISSUE THREAD

**Issue by sthivaios** [munin-monitoring/munin-node-win32#90]
![Screenshot 2023-06-30 011554](https://github.com/munin-monitoring/munin-node-win32/assets/109022579/25011fa4-2bad-4b33-a2e7-f3b2b34a0631)

**Comment by singularcitrus** [comment]
Thank you for bringing this to our attention, even if you were rude. This is an open source (stale) project, feel free to look at the code to verify that it is in fact safe. You are also more than welcome to submit a pull request suggesting a fix.

Further if you feel that our binary is unsafe you are also more than welcome to compile it yourself after cloning the repo. 

I have also take the liberty of uploading the github release binary to virustotal and there are indeed false positive detections as indicated in the screenshot.

Also thank you @yunal for fixing the issue title.
